theme: jekyll-theme-minimal
title: Ingrid Martin - Postdoctoral Research Associate
description: I'm a Postdoctoral Research Associate at the Centre for Neuroimaging Sciences at Kings College, London.
		
